# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QSize
from PyQt6.QtGui import QIcon
from pyqt6_multiselect_combobox import MultiSelectComboBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1035, 690)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scanner_wrapper = QtWidgets.QFrame(parent=self.centralwidget)
        self.scanner_wrapper.setGeometry(QtCore.QRect(190, 100, 651, 161))
        self.scanner_wrapper.setStyleSheet("QFrame {\n"
                                           "    border:1px solid #000;\n"
                                           "}\n"
                                           "QLabel {\n"
                                           "    border:none;\n"
                                           "}")
        self.scanner_wrapper.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.scanner_wrapper.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.scanner_wrapper.setObjectName("scanner_wrapper")
        self.label = QtWidgets.QLabel(parent=self.scanner_wrapper)
        self.label.setGeometry(QtCore.QRect(10, 0, 171, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.scanner_wrapper)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.scanner_wrapper)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.scanner_wrapper)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.exchange_list = QtWidgets.QComboBox(parent=self.scanner_wrapper)
        self.exchange_list.setGeometry(QtCore.QRect(150, 30, 351, 31))
        self.exchange_list.setObjectName("exchange_list")
        self.exchange_list.setCurrentIndex(-1)
        self.black_list_symbols = MultiSelectComboBox(parent=self.scanner_wrapper)
        self.black_list_symbols.setGeometry(QtCore.QRect(150, 70, 311, 31))
        self.black_list_symbols.setObjectName("black_list_symbols")
        self.black_list_symbols.setCurrentIndex(-1)
        self.black_list_symbols.setDisplayType("text")
        self.black_list_symbols.setOutputType("data")
        self.black_list_symbols.setDisplayDelimiter(", ")
        self.reset_black_list = QtWidgets.QPushButton(
            icon=QIcon("./assets/icons/reset.svg"),
            parent=self.scanner_wrapper
        )
        self.reset_black_list.setGeometry(QtCore.QRect(470, 70, 31, 31))
        self.reset_black_list.setToolTip("Reset black list")
        self.reset_black_list.setObjectName("reset_black_list")
        self.reset_black_list.setFixedSize(30, 30)
        self.reset_black_list.setIconSize(QSize(30, 30))
        self.reset_black_list.setStyleSheet("QPushButton{\n"
                                            "    background: #fff;\n"
                                            "}")

        self.min_transaction_amount = QtWidgets.QDoubleSpinBox(parent=self.scanner_wrapper)
        self.min_transaction_amount.setGeometry(QtCore.QRect(180, 110, 131, 31))
        self.min_transaction_amount.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignTrailing | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.min_transaction_amount.setObjectName("min_transaction_amount")
        self.min_transaction_amount.setMinimum(0.00)
        self.min_transaction_amount.setMaximum(1000000.00)
        self.start_scan = QtWidgets.QPushButton(
            icon=QIcon("./assets/icons/magical.svg"),
            parent=self.scanner_wrapper
        )
        self.start_scan.setGeometry(QtCore.QRect(510, 30, 131, 41))
        self.start_scan.setObjectName("start_scan")
        self.start_scan.setStyleSheet("QPushButton{\n"
                                      "    background: #fff;\n"
                                      "    color: #000;\n"
                                      "}")

        self.stop_scan = QtWidgets.QPushButton(
            icon=QIcon("./assets/icons/stop-scan.svg"),
            parent=self.scanner_wrapper
        )
        self.stop_scan.setGeometry(QtCore.QRect(510, 80, 131, 41))
        self.stop_scan.setObjectName("stop_scan")
        self.stop_scan.setStyleSheet("QPushButton{\n"
                                      "    background: #fff;\n"
                                      "    color: #000;\n"
                                      "}")
        self.sandbox_mode = QtWidgets.QCheckBox(parent=self.scanner_wrapper)
        self.sandbox_mode.setGeometry(QtCore.QRect(330, 110, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.sandbox_mode.setFont(font)
        self.sandbox_mode.setObjectName("sandbox_mode")
        self.result_set_wrapper = QtWidgets.QFrame(parent=self.centralwidget)
        self.result_set_wrapper.setGeometry(QtCore.QRect(10, 270, 1011, 351))
        self.result_set_wrapper.setStyleSheet("QFrame{\n"
                                              "    border:1px solid #000;\n"
                                              "}")
        self.result_set_wrapper.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.result_set_wrapper.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.result_set_wrapper.setObjectName("result_set_wrapper")
        self.console = QtWidgets.QTextEdit(parent=self.result_set_wrapper)
        self.console.setEnabled(True)
        self.console.setGeometry(QtCore.QRect(0, 0, 1011, 351))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.console.setFont(font)
        self.console.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.console.setAutoFillBackground(True)
        self.console.setStyleSheet("QTextEdit{\n"
                                   "    background: #000;\n"
                                   "}")
        self.console.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.console.setReadOnly(True)
        self.console.setObjectName("console")
        self.config_warnings = QtWidgets.QFrame(parent=self.centralwidget)
        self.config_warnings.setGeometry(QtCore.QRect(20, 20, 991, 71))
        self.config_warnings.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.config_warnings.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.config_warnings.setObjectName("config_warnings")
        self.warning_message = QtWidgets.QLabel(parent=self.config_warnings)
        self.warning_message.setGeometry(QtCore.QRect(0, 0, 991, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warning_message.sizePolicy().hasHeightForWidth())
        self.warning_message.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.warning_message.setFont(font)
        self.config_warnings.setStyleSheet("QFrame{\n"
                                           "    color:rgb(252, 152, 3);\n"
                                           "    background:#fff;\n"
                                           "    border-radius: 15px;\n"
                                           "}")
        self.warning_message.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.warning_message.setAutoFillBackground(True)
        self.warning_message.setObjectName("warning_message")
        self.config_warnings.hide()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionAPI_MANAGEMENT = QtGui.QAction(parent=MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionAPI_MANAGEMENT.setFont(font)
        self.actionAPI_MANAGEMENT.setObjectName("actionAPI_MANAGEMENT")
        self.actionPreferences = QtGui.QAction(parent=MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.actionPreferences.setFont(font)
        self.actionPreferences.setObjectName("actionPreferences")
        self.toolBar.addAction(self.actionAPI_MANAGEMENT)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPreferences)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CryptoBot"))
        self.label.setText(_translate("MainWindow", "Triangular Arbitrage"))
        self.label_2.setText(_translate("MainWindow", "Select Exchange"))
        self.label_3.setText(_translate("MainWindow", "Symbols Black List"))
        self.label_4.setText(_translate("MainWindow", "Min transaction Amount"))
        self.exchange_list.setToolTip(_translate("MainWindow", "Select the Exchange ID"))
        self.exchange_list.setPlaceholderText(_translate("MainWindow", "--Select an Exchange--"))
        self.black_list_symbols.setToolTip(_translate("MainWindow", "You can select the coins symbols to black list when starting to scan"))
        self.black_list_symbols.setPlaceholderText(_translate("MainWindow", "--Select coins--"))
        self.start_scan.setToolTip(_translate("MainWindow", "Start the scan with or without Orders"))
        self.start_scan.setText(_translate("MainWindow", "Launch Scan"))
        self.stop_scan.setToolTip(_translate("MainWindow", "Stop the scan process"))
        self.stop_scan.setText(_translate("MainWindow", "Stop Scan"))
        self.sandbox_mode.setText(_translate("MainWindow", "Make Buy & Sell Orders"))
        self.reset_black_list.setToolTip(_translate("MainWindow", "Reset black list"))
        self.console.setToolTip(_translate("MainWindow", "CryptoBot Result"))
        self.warning_message.setText(_translate("MainWindow", "test"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionAPI_MANAGEMENT.setText(_translate("MainWindow", "API Management"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
